// Generated by Tools/icon_gen.py --status --write. Edit status_icons.json.
#pragma once
#include "status_icon_layout.h"
namespace astra {
static const uint8_t status_data_battery[] = {
  0x00, 0x00, 0xFC, 0xFF, 0x06, 0x80, 0xF6, 0xBF, 0xF6, 0xBF, 0xF6, 0xBF, 0xF6, 0xBF, 0x06, 0x80,
  0xFC, 0xFF, 0x00, 0x00,
};
static const Bitmap status_bitmap_battery = {status_data_battery, 16, 10, sizeof(status_data_battery)};
static const uint8_t status_data_wifi[] = {
  0x00, 0x00, 0x00, 0x0F, 0x80, 0x01, 0x60, 0x00, 0x20, 0x0E, 0x10, 0x03, 0x98, 0x00, 0xC8, 0x08,
  0x48, 0x0C, 0x48, 0x0E,
};
static const Bitmap status_bitmap_wifi = {status_data_wifi, 14, 10, sizeof(status_data_wifi)};
static const uint8_t status_data_tf[] = {
  0x00, 0x00, 0xFE, 0x03, 0xFE, 0x0F, 0xFE, 0x21, 0xFE, 0x3F, 0xFE, 0x21, 0xFE, 0x3F, 0xFE, 0x21,
  0xFE, 0x3F, 0x00, 0x00,
};
static const Bitmap status_bitmap_tf = {status_data_tf, 14, 10, sizeof(status_data_tf)};
static StatusIconEntry statusIconEntries[] = {
  {"battery", &status_bitmap_battery, true, &status_bitmap_battery, true},
  {"wifi", &status_bitmap_wifi, true, &status_bitmap_wifi, true},
  {"tf", &status_bitmap_tf, true, &status_bitmap_tf, true},
};
static const size_t statusIconEntryCount = 3;
}
