"""Status-bar resources: '#' = white/on, '.' = transparent/off. No menu inversion."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'Tools/icons/status_icons.json'
HEADER = ROOT / 'Astra/astra/status_icons_generated.h'
PREVIEW = ROOT / 'Tools/status_icons_preview.png'


def validate(doc):
    resources = {}
    for entry in doc['bitmaps']:
        name, rows = entry['name'], entry['rows']
        if not isinstance(name, str) or not re.fullmatch(r'[a-z][a-z0-9_]*', name) or name in resources:
            raise ValueError('Invalid or duplicate bitmap name')
        if not isinstance(rows, list) or not rows or not all(isinstance(r, str) for r in rows):
            raise ValueError(name + ': rows must be non-empty strings')
        width = len(rows[0])
        if not 1 <= width <= 255 or not 1 <= len(rows) <= 255:
            raise ValueError(name + ': dimensions must be 1..255')
        if any(len(r) != width or set(r) - {'#', '.'} for r in rows):
            raise ValueError(name + ': unequal rows or invalid pixels')
        resources[name] = rows
    ids = set()
    for entry in doc['layout']:
        name = entry['id']
        if not isinstance(name, str) or not re.fullmatch(r'[a-z][a-z0-9_]*', name) or name in ids:
            raise ValueError('Invalid or duplicate slot ID')
        ids.add(name)
        if entry['bitmap'] not in resources or type(entry['visible']) is not bool:
            raise ValueError(name + ': invalid resource or visibility')
    return resources


def encode(rows):
    width = len(rows[0])
    return bytes(sum(1 << bit for bit in range(8)
                     if x + bit < width and row[x + bit] == '#')
                 for row in rows for x in range(0, width, 8))


def decode(data, width, height):
    stride = (width + 7) // 8
    if len(data) != stride * height:
        raise ValueError('Bitmap length mismatch')
    return [''.join('#' if data[y * stride + x // 8] & (1 << (x % 8)) else '.'
                    for x in range(width)) for y in range(height)]


def generate(doc):
    resources = validate(doc)
    lines = ['// Generated by Tools/icon_gen.py --status --write. Edit status_icons.json.',
             '#pragma once', '#include "status_icon_layout.h"', 'namespace astra {']
    for name, rows in resources.items():
        data = encode(rows)
        if decode(data, len(rows[0]), len(rows)) != rows:
            raise ValueError('Round-trip failure: ' + name)
        lines.append('static const uint8_t status_data_' + name + '[] = {')
        for i in range(0, len(data), 16):
            lines.append('  ' + ', '.join(f'0x{b:02X}' for b in data[i:i+16]) + ',')
        lines += ['};', f'static const Bitmap status_bitmap_{name} = '
                  f'{{status_data_{name}, {len(rows[0])}, {len(rows)}, sizeof(status_data_{name})}};']
    lines.append('static StatusIconEntry statusIconEntries[] = {')
    for entry in doc['layout']:
        bmp = 'status_bitmap_' + entry['bitmap']
        visible = str(entry['visible']).lower()
        lines.append(f'  {{"{entry["id"]}", &{bmp}, {visible}, &{bmp}, {visible}}},')
    if not doc['layout']:
        lines.append('  {nullptr, nullptr, false, nullptr, false}, // storage sentinel, count=0')
    lines += ['};', f'static const size_t statusIconEntryCount = {len(doc["layout"])};', '}', '']
    return '\n'.join(lines)


def preview(doc):
    from PIL import Image, ImageDraw
    resources = validate(doc)
    bar = Image.new('RGB', (128, 20), 'black')
    right = 126
    for entry in doc['layout']:
        rows = resources[entry['bitmap']]
        width, height = len(rows[0]), len(rows)
        x = right - width
        if not entry['visible'] or height > 19 or x - 4 < 32:
            continue
        for y, row in enumerate(rows):
            for col, value in enumerate(row):
                if value == '#':
                    bar.putpixel((x + col, (20-height)//2+y), (255,255,255))
        right = x - 2
    ImageDraw.Draw(bar).line((0,19,127,19), fill='white')
    scale = 6
    sheet = Image.new('RGB', (800, 190+len(resources)*160), '#202020')
    draw = ImageDraw.Draw(sheet)
    draw.text((16,12), 'Status bar layout (6x; title omitted)', fill='white')
    sheet.paste(bar.resize((768,120), Image.Resampling.NEAREST), (16,36))
    for index,(name,rows) in enumerate(resources.items()):
        top=180+index*160
        draw.text((16,top), f'{name} {len(rows[0])}x{len(rows)} (8x)', fill='white')
        im=Image.new('RGB',(len(rows[0]),len(rows)),'black')
        for y,row in enumerate(rows):
            for x,value in enumerate(row):
                if value=='#': im.putpixel((x,y),(255,255,255))
        sheet.paste(im.resize((im.width*8,im.height*8),Image.Resampling.NEAREST),(16,top+24))
    sheet.save(PREVIEW)
    print('[ OK ] Preview:', PREVIEW)


def run(write=False, make_preview=False):
    doc = json.loads(SOURCE.read_text(encoding='utf-8'))
    expected = generate(doc)
    if write:
        HEADER.write_text(expected, encoding='utf-8')
    if not HEADER.exists() or HEADER.read_text(encoding='utf-8') != expected:
        raise ValueError('Status resource header differs; run --status --write')
    print('[ OK ] Status resources, dimensions, defaults and layout match source')
    if make_preview:
        preview(doc)
